### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Arise903** [maxfong/MFSIdentifier#1]
你说明文档那个里面的是否所表示的意思是什么?? 是表示的是改变,否表示的不改变.??

**Comment by maxfong** [comment]
@lilovexin 是否刷机指的是系统环境是否变化

**Comment by maxfong** [comment]
@lilovexin 你理解是对的
是否刷机对应的是系统环境是否变化
APP重装对应的是应用是否卸载重新安装

**Comment by Arise903** [comment]
谢谢解答,你的demo运行不起来,你看看什么问题??

**Comment by Arise903** [comment]
在模拟器运行没有问题,真机6S iOS版本10.3.1

**Comment by maxfong** [comment]
@lilovexin 
不好意思，因为支持Carthage要把Mach-O设为Dynamic Library，在Demo里Embedded Binaries忘记加上Framework了，你更新最新的master分支，手机也能运行了

**Comment by Arise903** [comment]
好了,现在真机可以运行了.
