### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by JHCoderLion** [maxfong/MFSIdentifier#2]
请问你是否玩过钱咖或者试客小兵类似这种的应用,   我们的APP是需要检测用户是否在App Store下载  是否越狱   是否第一次下载   是否删除后下载   如果是当前手机 当前的账号都是第一次下载  则发送对应的奖励

**Comment by maxfong** [comment]
@JHCoderLion 
是否在App Store下载:一般是应用内添加refid标识对应渠道
是否越狱:这个能查得到
是否第一次下载:现在KeyChain可用，所以查询存储在KeyChain的数据，存在则表示不是第一次安装，集合iCloud刷机也能判断
是否删除后下载:添加校验逻辑，给应用累加一个标识符，再根据是否第一次下载判断是否重新安装
如果是当前手机：可以根据Telephony、屏幕分辨率、以及设备名称等，再根据存储的标识符做校验
当前的账号都是第一次下载:以上问题都解决，这个也就知道了

KeyChain不可用时，可用Safari Cookie、iCloud替代
很多这类应用会有一个企业助手，可调用的私有API的

**Comment by JHCoderLion** [comment]
感谢你的解答, 非常详细和实用,  还有一个不太了解 "是否在App Store下载:一般是应用内添加refid标识对应渠道"   这个  refid  是什么?

**Comment by maxfong** [comment]
@JHCoderLion 你自己定义的，比如App Store为10000，PP助手为10001等等，iOS应用 大部分都是App Store下载，小渠道或者越狱取到的量很少的
