### ISSUE TITLE
恢复出厂设置这种怎么做的呢

### ISSUE THREAD

**Issue by niuxinghua** [maxfong/MFSIdentifier#4]

**Comment by maxfong** [comment]
MFSIdentifier添加了iCloud支持，刷机后需登录apple id再下载应用，此时已经能获取存储在iCloud中的标识符了

**Comment by maxfong** [comment]
@niuxinghua MFSIdentifier添加了iCloud支持，刷机后需登录apple id再下载应用，此时已经能获取存储在iCloud中的标识符了

**Comment by niuxinghua** [comment]
意思是说你的这uuid可以保证任何情况下的唯一性是吧

**Comment by maxfong** [comment]
越狱环境或企业应用可能获取不到的，不能保证任何情况，MFSIdentifier只是一种可用的方法 ^_^

**Comment by niuxinghua** [comment]
牛逼啊  。。。。

**Comment by maxfong** [comment]
这几种存储方式的组合使用，发出来看是否有一些隐藏问题
