### ISSUE TITLE
两个不同teamID的app 可以获取一样的唯一ID吗？

### ISSUE THREAD

**Issue by Zkim** [maxfong/MFSIdentifier#6]

**Comment by maxfong** [comment]
@Zkim
逻辑先理一下
Safari Cookie是共享的，优先级高于iCloud，并且第一次获取值方式是idfa，所以有可能最终取值是一样。

有一种情况：安装第二个app前重置了idfa  
这个库用了scheme区分，所以不同的app取到的值不一样，存储到iCloud的也不一样。

如果你想获取不在teamID的多个app有相同标识符，可以试试重写Safari Cookie，但我觉得那样不安全

**Comment by Zkim** [comment]
Safari Cookie第一次获取值方式是idfa  ，但是idfa是用户可以主动关闭的，如果用户关闭或者刷机  是否会影响唯一id的唯一性呢？

**Comment by maxfong** [comment]
@Zkim 
IDFA -> IDFV -> NSUUID

关闭没问题，可以取IDFV
刷机后的取值要看iCloud了，首次安装应用需要登录appid，就能将数据同步到设备了
只要打开一次，Safari和应用缓存又会把值存好，然后以此类推
