### ISSUE TITLE
iOS 11 下 tabbar 会多出一个tab

### ISSUE THREAD

**Issue by yunkai909** [maxfong/MFSIdentifier#7]
![45e4db44-882b-434b-a694-7d18410e23b3](https://user-images.githubusercontent.com/8436462/30636821-13a8e2b0-9e29-11e7-9830-38e5960200f0.png)

ios11 下不执行以下代码。

**Comment by li-zhe** [comment]
遇到了同样的问题，多了一个tabBarItem

**Comment by maxfong** [comment]
@BestKai @li-zhe 升级了一个版本

**Comment by maxfong** [comment]
@BestKai @li-zhe 已修复，请测试下1.0.1版本

**Comment by li-zhe** [comment]
@maxfong  请问这里为什么要请求那个地址，而且还把CFBundleURLSchemes的第一个当参数传过去。

**Comment by maxfong** [comment]
@li-zhe 
1.请求地址是为了把值存储在当前域名的cookie中
2.通过scheme唤起客户端获取值

**Comment by yunkai909** [comment]
还是不行啊，还是会有多余的一个tabbar。问题出在我上面截图的没有执行 removeFromParentViewController。

**Comment by maxfong** [comment]
@BestKai 多于一个tabbar是什么样能截图吗？你试着创建个简单的工程使用这个库，看是否有问题，我这边测试ok的。
如果最后真有问题，可以试着删除Safari Cookie代码。

**Comment by yunkai909** [comment]
@maxfong   https://github.com/BestKai/MFSIdentifyDemo.git  这是demo地址，我测试的是只有在设置了 URL  types  的情况下会出现多一个的情况。

**Comment by maxfong** [comment]
@BestKai Tabbar的确有问题，添加Item的问题在1.0.2解决了
Tabbar启动变色问题暂时还没找到解决方案，可以试着在-application:didFinishLaunchingWithOptions:中设置[MFSSafariIDManager enable:NO];

**Comment by yunkai909** [comment]
好的。期待更完美的解决方案。辛苦

**Comment by maxfong** [comment]
@BestKai :-D
