### ISSUE TITLE
怎么让自己的私有pod库支持Carthage

### ISSUE THREAD

**Issue by huakucha** [maxfong/MFSIdentifier#8]
如题：怎么让自己的私有pod库支持Carthage  自己无论是在引用其他的三方库还是自己的私有库 都会发现有些库不支持Carthage   让Carthage的前置条件是什么啊

**Comment by maxfong** [comment]
@huakucha 使用git即可支持

**Comment by maxfong** [comment]
@huakucha 
配置好工程，push到自己仓库，
配置文件内github换成git，如

git "https://xxx/xxx.git"即可

**Comment by huakucha** [comment]
你所说的配置文件是Carthage的配置文件吗（Cartfile）

**Comment by maxfong** [comment]
@huakucha 是的

**Comment by huakucha** [comment]
文件： github "https://github.com/rentzsch/jrswizzle.git"
命令：carthage update --platform iOS
结果：Dependency "jrswizzle" has no shared framework schemes for any of the platforms: iOS
这种原因是什么

**Comment by maxfong** [comment]
@huakucha 
"配置好工程"这句话你研究下
比如：选择 Manager Schemes，勾上shared，这步有做吗？

**Comment by huakucha** [comment]
明白了 你的构建的MFSIdentifier确实勾上shared  谢谢了...

**Comment by maxfong** [comment]
@huakucha 
配置Carthage时需选择Manager Schemes并对需要编译的Target勾选Shared，否则会出现提示 
Dependency "项目名" has no shared framework schemes

是因为Carthage编译基于xcodebuild，-workspace编译时需要-scheme参数
而我们配置.gitignore中排除了xcuserdata
git下载的工程(或删掉xcuserdata)后运行xcodebuild -list可以发现不存在Schemes一项
勾选Shared后会在.xcodeproj创建xcshareddata目录，里面保存着.xcscheme

**Comment by huakucha** [comment]
pod package原理是不是也是基于xcodebuild

**Comment by maxfong** [comment]
@huakucha 是的
